version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_URL: "postgres://user:password@db:5432/appdb?sslmode=disable"
      REDIS_URL: "redis://redis:6379"
      GIN_MODE: "debug"
    ports:
      - "0:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
