// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        int32
	Content   string
	CreatedAt pgtype.Timestamp
}
